/*
 * Spread implementation of JGCS - Group Communication Service.
 * Copyright (C) 2006,2013 Jose' Orlando Pereira
 *
 * http://github.com/jopereira/jgcs
 * 
 * See COPYING for licensing details.
 */

package net.sf.jgcs.spread;

import net.sf.jgcs.GroupException;

/**
 * This class encapsulated errors generated by spread.
 */
public class SpException extends GroupException {

	private static final long serialVersionUID = -3094837861815069324L;

	public SpException(int error, String desc) {
		super((desc!=null?desc:((error<=ILLEGAL_SPREAD&&error>=ILLEGAL_RECEIVERS)?errors[-(error-ILLEGAL_SPREAD)]:unknown))+" ("+error+")");
		this.error=error;
	}

	public int getError() {
		return error;
	}

	public static final int ILLEGAL_SPREAD=-1;
	public static final int COULD_NOT_CONNECT=-2;
	public static final int REJECT_QUOTA=-3;
	public static final int REJECT_NO_NAME=-4;
	public static final int REJECT_ILLEGAL_NAME=-5;
	public static final int REJECT_NOT_UNIQUE=-6;
	public static final int REJECT_VERSION=-7;
	public static final int CONNECTION_CLOSED=-8;
	public static final int REJECT_AUTH=-9;

	public static final int ILLEGAL_SESSION=-11;
	public static final int ILLEGAL_SERVICE=-12;
	public static final int ILLEGAL_MESSAGE=-13;
	public static final int ILLEGAL_GROUP=-14;
	public static final int BUFFER_TOO_SHORT=-15;
	public static final int GROUPS_TOO_SHORT=-16;
	public static final int MESSAGE_TOO_LONG=-17;

	public static final int ILLEGAL_PARAM=-24;
    public static final int WOULD_BLOCK=-25;
    public static final int ILLEGAL_MESSAGE_TYPE=-26;
    public static final int ILLEGAL_STATE=-27;
    public static final int ILLEGAL_RECEIVERS=-28;
	
	private int error;

	private static final String unknown="Unknown error";
	
	private static final String errors[]={
		"Illegal spread was provided",
		"Could not connect. Is Spread running?",
		"Connection rejected, too many users",
		"Connection rejected, no name was supplied",
		"Connection rejected, illegal name",
		"Connection rejected, name not unique",
		"Connection rejected, library does not fit daemon",
		"Connection closed by spread",
		"Connection rejected, authentication failed",

		unknown,

		"Illegal session was supplied",
		"Illegal service request",
		"Illegal message",
		"Illegal group",
		"The supplied buffer was too short",
		"The supplied groups list was too short",
		"The message body + group names was too large to fit in a message",

		unknown,
		unknown,
		unknown,
		unknown,
		unknown,
		unknown,

        "Illegal parameter (eg a negative size) passed to a function",
        "Function call would have blocked",
        "Illegal message type (int16) used, value < FL_MIN_LEGAL_MESS_TYPE",
        "Function call peformed in a prohibited state",
        "Illegal receivers specified"
	};
};
