/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_jgcs_spread_jni_Mailbox */

#ifndef _Included_net_sf_jgcs_spread_jni_Mailbox
#define _Included_net_sf_jgcs_spread_jni_Mailbox
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sf_jgcs_spread_jni_Mailbox
 * Method:    C_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sf_jgcs_spread_jni_Mailbox_C_1init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
