/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_jgcs_spread_jni_Mailbox_MulticastArgs */

#ifndef _Included_net_sf_jgcs_spread_jni_Mailbox_MulticastArgs
#define _Included_net_sf_jgcs_spread_jni_Mailbox_MulticastArgs
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
