/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_jgcs_spread_jni_Mailbox_ReceiveArgs */

#ifndef _Included_net_sf_jgcs_spread_jni_Mailbox_ReceiveArgs
#define _Included_net_sf_jgcs_spread_jni_Mailbox_ReceiveArgs
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
