/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_jgcs_spread_jni_FlMailbox */

#ifndef _Included_net_sf_jgcs_spread_jni_FlMailbox
#define _Included_net_sf_jgcs_spread_jni_FlMailbox
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sf_jgcs_spread_jni_FlMailbox
 * Method:    C_connect
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZZ)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jgcs_spread_jni_FlMailbox_C_1connect
  (JNIEnv *, jobject, jstring, jstring, jboolean, jboolean);

/*
 * Class:     net_sf_jgcs_spread_jni_FlMailbox
 * Method:    C_disconnect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sf_jgcs_spread_jni_FlMailbox_C_1disconnect
  (JNIEnv *, jobject);

/*
 * Class:     net_sf_jgcs_spread_jni_FlMailbox
 * Method:    C_join
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jgcs_spread_jni_FlMailbox_C_1join
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_sf_jgcs_spread_jni_FlMailbox
 * Method:    C_leave
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jgcs_spread_jni_FlMailbox_C_1leave
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_sf_jgcs_spread_jni_FlMailbox
 * Method:    C_flush
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jgcs_spread_jni_FlMailbox_C_1flush
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_sf_jgcs_spread_jni_FlMailbox
 * Method:    C_multicast
 * Signature: (Lnet/sf/jgcs/spread/jni/Mailbox/MulticastArgs;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jgcs_spread_jni_FlMailbox_C_1multicast
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     net_sf_jgcs_spread_jni_FlMailbox
 * Method:    C_subgroupcast
 * Signature: (Lnet/sf/jgcs/spread/jni/Mailbox/MulticastArgs;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jgcs_spread_jni_FlMailbox_C_1subgroupcast
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     net_sf_jgcs_spread_jni_FlMailbox
 * Method:    C_receive
 * Signature: (Lnet/sf/jgcs/spread/jni/Mailbox/ReceiveArgs;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jgcs_spread_jni_FlMailbox_C_1receive
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     net_sf_jgcs_spread_jni_FlMailbox
 * Method:    C_parseView
 * Signature: (Lnet/sf/jgcs/spread/jni/Mailbox/ViewInfo;Lnet/sf/jgcs/spread/jni/Mailbox/MulticastArgs;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jgcs_spread_jni_FlMailbox_C_1parseView
  (JNIEnv *, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
